- name: Install aptitude using apt
  apt:
    name: aptitude
    state: latest
    update_cache: yes
    force_apt_get: yes

- name: Update et prerequis pour depot
  apt:
   update_cache: yes
   pkg:
     - apt-transport-https
     - curl
     - ca-certificates
     - gnupg
     - lsb-release
     - software-properties-common
     - python3-pip
     - virtualenv
     - python3-setuptools
