- name: Update et prerequis pour depot
  apt:
   update_cache: yes
   cache_valid_time: 3600
   name:
    - apt-transport-https
    - curl
    - ca-certificates
    - gnupg
    - lsb-release
    - software-properties-common
    - python3-pip
    - virtualenv
    - python3-setuptools
   force_apt_get: yes
   state: latest
  